QUOTES = [
    '"Здесь меня не пробить" \n(с) нейромонах П.',
    '"Ладно Павел! Спасибо за поддержку!" \n(с) тот самый А.',
    '"Всем добрейшего денечка" \n(с) статистически значимый А.',
    '"О, кота размотало" \n(c) статистически значимый А.',
    '"Трещины это всегда плохо!" \n(c) нейромонах П.',
    '"Можете зайти к нам в зум, помочь? Необходимо решить очень важный момент! <...> На словах не обьяснить" \n(c) тот самый А.',
    '"Делать всё нужно с кайфом" \n(c) статистически значимый А.',
    '"Всем хорошего вечерочка, доделывайте задания потихонечку [а я в баньку пошел]" \n(c) статистически значимый А.',
    '"Вот псина, вот еще псина. Это я ласково" \n(c) нейромонах П.',
    '"Если нравится - надо тыкать и всё" \n(c) нейромонах П.',
    '"Мы просто ее палочкой потыкаем и посмотрим, что будет" \n(c) нейромонах П.',
]

QUOTE_FORM = '" " \n(c) '

category_to_channels = {
    'новости': [
        'https://t.me/breakingmash',
        'https://t.me/lentachold',
        'https://t.me/astrapress',
        'https://t.me/lentachold',
        'https://t.me/theinsider',
        'https://t.me/otsuka_bld',
        'https://t.me/meduzalive',
        'https://t.me/guardian',
    ],
    'юмор': [
        'https://t.me/ia_panorama',
        'https://t.me/dvachannel',
        'https://t.me/pezduzalive',
        'https://t.me/mudak',
        'https://t.me/cats_cats',
        'https://t.me/Reddit',
        'https://t.me/paperpublic',
        'https://t.me/thedankestmemes',
        'https://t.me/memes',
        'https://t.me/community_memy',
    ],
    'технологии': [
        'https://t.me/bugnotfeature',
        'https://t.me/prostinas',
        'https://t.me/it_teech',
        'https://t.me/rozetked',
        'https://t.me/yandex',
        'https://t.me/junior_developer_ua',
        'https://t.me/htech_plus',
        'https://t.me/cyberfreek',
        'https://t.me/python2day',
        'https://t.me/addmeto',
    ],
    'экономика': [
        'https://t.me/zeroton',
        'https://t.me/guriev_sm',
        'https://t.me/financelist',
        'https://t.me/proeconomics',
        'https://t.me/hoolinomics',
        'https://t.me/dohod',
        'https://t.me/prime1',
        'https://t.me/AK47pfl',
        'https://t.me/forbesrussia',
        'https://t.me/selfinvestor',
    ],
    'игры': [
        'https://t.me/+VIuvvPWhb-mR4BRq',
        'https://t.me/Dota2',
        'https://t.me/egs_tg',
        'https://t.me/vgtimes',
        'https://t.me/stopgamenews',
        'https://t.me/PROgame_news',
        'https://t.me/GamezTop7',
        'https://t.me/gamerbay',
        'https://t.me/combobreaker',
        'https://t.me/progamedev',
    ],
    'спорт': [
        'https://t.me/championat',
        'https://t.me/Match_TV',
        'https://t.me/myachPRO',
        'https://t.me/sportsru',
        'https://t.me/QryaProDucktion',
        'https://t.me/sjbodyfit',
        'https://t.me/fiztransform',
        'https://t.me/sportsmens1',
        'https://t.me/runforhealth',
        'https://t.me/sportazarto',
    ],
}