QUOTES = [
    '"***Здесь меня не пробить***" \n\n(с) нейро-сенсей П.',
    '"***Ладно Павел! Спасибо за поддержку!***" \n\n(с) тот самый А.',
    '"***Всем добрейшего денёчка***" \n\n(с) статистически очень значимый А.',
    '"***О, кота размотало***" \n\n(c) статистически очень значимый А.',
    '"***Трещины это всегда плохо!***" \n\n(c) нейро-сенсей П.',
    '"***Можете зайти к нам в зум, помочь? Необходимо решить очень важный момент!*** <...> ***На словах не обьяснить***" \n\n(c) тот самый А.',
    '"***Делать всё нужно с кайфом***" \n\n(c) статистически очень значимый А.',
    '"***Всем хорошего вечерочка, доделывайте задания потихонечку [а я в баньку пошел]***" \n\n(c) статистически очень значимый А.',
    '"***Вот псина, вот еще псина. Это я ласково***" \n\n(c) нейро-сенсей П.',
    '"***Если нравится - надо тыкать и всё***" \n\n(c) нейро-сенсей П.',
    '"***Мы просто ее палочкой потыкаем и посмотрим, что будет***" \n\n(c) нейро-сенсей П.',
    '"***Всё отлично, только вчера переборщил немного, сегодня руки болят. Ну ничего, всё было с кайфом!***" \n\n(c) статистически очень значимый А.',
    '"***Ну и что в этом такого? В чем научная новизна вашей работы?!***" \n\n(c) тот самый А.',
]

QUOTE_FORM = '"*** ***" \n\n(c) '

category_to_channels = {
    'новости': [
        'https://t.me/breakingmash',
        'https://t.me/lentachold',
        'https://t.me/astrapress',
        'https://t.me/lentachold',
        'https://t.me/theinsider',
        'https://t.me/otsuka_bld',
        'https://t.me/meduzalive',
        'https://t.me/guardian',
    ],
    'юмор': [
        'https://t.me/ia_panorama',
        'https://t.me/dvachannel',
        'https://t.me/pezduzalive',
        'https://t.me/mudak',
        'https://t.me/cats_cats',
        'https://t.me/Reddit',
        'https://t.me/paperpublic',
        'https://t.me/thedankestmemes',
        'https://t.me/memes',
        'https://t.me/community_memy',
    ],
    'технологии': [
        'https://t.me/bugnotfeature',
        'https://t.me/prostinas',
        'https://t.me/it_teech',
        'https://t.me/rozetked',
        'https://t.me/yandex',
        'https://t.me/junior_developer_ua',
        'https://t.me/htech_plus',
        'https://t.me/cyberfreek',
        'https://t.me/python2day',
        'https://t.me/addmeto',
    ],
    'экономика': [
        'https://t.me/zeroton',
        'https://t.me/guriev_sm',
        'https://t.me/financelist',
        'https://t.me/proeconomics',
        'https://t.me/hoolinomics',
        'https://t.me/dohod',
        'https://t.me/prime1',
        'https://t.me/AK47pfl',
        'https://t.me/forbesrussia',
        'https://t.me/selfinvestor',
    ],
    'игры': [
        'https://t.me/+VIuvvPWhb-mR4BRq',
        'https://t.me/Dota2',
        'https://t.me/egs_tg',
        'https://t.me/vgtimes',
        'https://t.me/stopgamenews',
        'https://t.me/PROgame_news',
        'https://t.me/GamezTop7',
        'https://t.me/gamerbay',
        'https://t.me/combobreaker',
        'https://t.me/progamedev',
    ],
    'спорт': [
        'https://t.me/championat',
        'https://t.me/Match_TV',
        'https://t.me/myachPRO',
        'https://t.me/sportsru',
        'https://t.me/QryaProDucktion',
        'https://t.me/sjbodyfit',
        'https://t.me/fiztransform',
        'https://t.me/sportsmens1',
        'https://t.me/runforhealth',
        'https://t.me/sportazarto',
    ],
}